// esbuild.config.mjs
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { promises as fs } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// D1 Task 4 (Plan 03): post-Vue, main.ts's `import "./styles-source.css"` is the only CSS
// source esbuild bundles into main.css (no more SFC scoped-style extraction) — this plugin
// just copies that bundled main.css to styles.css, which is what Obsidian loads.
const copyToStylesPlugin = {
  name: "copy-css-to-styles",
  setup(build) {
    build.onEnd(async () => {
      try {
        await fs.copyFile("main.css", "styles.css");
      } catch { /* ignore if no CSS yet */ }
    });
  }
};

const yamlLoaderPlugin = {
  name: "yaml-loader",
  setup(build) {
    build.onLoad({ filter: /\.ya?ml$/ }, async (args) => {
      try {
        const text = await fs.readFile(args.path, 'utf8');
        return {
          contents: `export default ${JSON.stringify(text)};`,
          loader: 'js',
        };
      } catch (error) {
        return {
          errors: [{
            text: `Failed to load YAML file: ${error.message}`,
            location: { file: args.path }
          }]
        };
      }
    });
  }
};

/**
 * SC-125 (review L3) — the compendium migration map ships as raw TEXT, not as parsed
 * data. esbuild's default `.json` loader would inline it as a JS object literal, which
 * the JS engine then builds at plugin load: ~390 KiB of source, a measured ~6.7 ms and
 * ~0.7 MB retained on EVERY startup, for a feature that runs at most once in a vault's
 * lifetime. As a string it costs a string; `src/data/CompendiumMigration.ts` parses it
 * lazily on first use (see `migrationMap()` there, which accepts both shapes because
 * ts-jest still resolves the import as parsed JSON).
 *
 * Scoped to this one file on purpose — a blanket `.json: "text"` loader would silently
 * change the meaning of any future JSON import.
 */
const migrationMapTextPlugin = {
  name: "migration-map-text",
  setup(build) {
    build.onLoad({ filter: /src[\\/]data[\\/]migrationMap\.json$/ }, async (args) => ({
      // Re-serialised compact: the committed file is pretty-printed so a human can
      // review the diff line by line, but the bundle has no use for 45 KiB of indentation.
      contents: `export default ${JSON.stringify(
        JSON.stringify(JSON.parse(await fs.readFile(args.path, "utf8"))),
      )};`,
      loader: "js",
    }));
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins
  ],
  format: "cjs",
  // JS target stays es2018 (unrelated to this fix — Obsidian's plugin runtime already
  // requires es2018+). "chrome106" is added purely to give esbuild's CSS pipeline a browser
  // target: esbuild keys its CSS-nesting downleveling off browser-target entries, not JS
  // version strings, so without a browser target native CSS nesting in styles-source.css
  // passes through the bundle unflattened. Chrome 106 matches Obsidian's actual bundled
  // Electron/Chromium floor on older desktop installs (SC-122; see
  // .superpowers/sdd/sc121-audit/nesting-verification.md), which has zero CSS-nesting
  // support and silently drops nested rules at parse time.
  target: ["es2018", "chrome106"],
  logLevel: "info",
  sourcemap: prod ? false : true,
  treeShaking: true,
  outfile: "main.js",
  tsconfig: "tsconfig.json",
  minify: prod,
  plugins: [
	copyToStylesPlugin,
	migrationMapTextPlugin,
	yamlLoaderPlugin
  ],
  define: {
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development')
  }
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
