// D8 Task 2 (spec §1.5) — block addressing without `getSectionInfo`. The sidebar has no
// MarkdownPostProcessorContext, so it can't get block identity for free the way
// ReadingModeBlockHost does; instead every block bound to the sidebar carries a durable
// `_dse_anchor: <id>` line inside its YAML body (round-trips through `serialize` for free
// as long as an element's model passes the key through — see the caveat in
// SidebarBlockHost.ts's file header). `findAnchoredBlock` re-derives the fence position by
// scanning for it, so it survives arbitrary line drift elsewhere in the note (unlike
// reading-mode's lineStart-keyed SessionStore) — the id travels IN the content, not
// alongside it.
import type { BlockInfo } from '../host/BlockHost';

/** Exported so `framework/pipeline.ts`'s `prepareModel` can exclude this exact key from
 *  what SCHEMA VALIDATION sees (D7 Task 10 finding — see that file's own doc for the
 *  full rationale: an `additionalProperties: false` element schema has no way to "know"
 *  about this sidebar-only key, so the two files must never drift on its spelling). */
export const ANCHOR_KEY = '_dse_anchor';
const ANCHOR_LINE = new RegExp(`^${ANCHOR_KEY}:\\s*['"]?([A-Za-z0-9_-]+)['"]?\\s*$`, 'm');

/** A fence-marker line: 3+ backticks/tildes (captured), then the rest of the line — the
 *  info string for an opener, or (after trimming) empty for a closer. Exported so
 *  registration.ts's `aliasAtLine` (a live-Editor, prefix-scan variant of the same
 *  open/close matching — see that function's doc for why it can't just call the
 *  content-string scanner below) shares this single regex instead of carrying its own
 *  copy; the two files must never test "is this a fence marker line" two different ways. */
export const FENCE_LINE = /^([`~]{3,})(.*)$/;

/** Small non-crypto id generator (Math.random-based — mobile-safe, no `crypto` node
 *  module; F1/D8 convention for anything that doesn't need cryptographic uniqueness). */
function generateAnchorId(): string {
	return Math.random().toString(16).slice(2, 8).padEnd(6, '0');
}

/** `body`'s dominant end-of-line style — CRLF only when every line break in `body` is
 *  `\r\n` (a mixed-EOL body, or one with no line breaks at all, defaults to LF). Mirrors
 *  `hero/model.ts`'s `detectEol` exactly (same rule, same rationale): the ONLY thing this
 *  feeds is the joiner in front of the freshly-appended anchor line below — `body`'s own
 *  bytes are never rewritten. FOLLOWUPS #28 LOW fix: without this, a CRLF-authored body
 *  got a bare `\n` joiner, leaving the stamped body mixed-EOL. */
function detectEol(body: string): '\r\n' | '\n' {
	const totalNewlines = (body.match(/\n/g) ?? []).length;
	if (totalNewlines === 0) return '\n';
	const crlfNewlines = (body.match(/\r\n/g) ?? []).length;
	return crlfNewlines === totalNewlines ? '\r\n' : '\n';
}

/** Finds an existing `_dse_anchor:` line in `body`, or appends a fresh one. Pure string
 *  op — `body` is a fenced block's BODY text (no fences), never the whole note). The
 *  joiner in front of the fresh anchor line matches `body`'s own dominant EOL (FOLLOWUPS
 *  #28 LOW), so a CRLF-authored block doesn't turn mixed-EOL on first stamp.
 *
 *  SC-158: this appends a LINE, which is only safe for a body whose grammar tolerates an
 *  unknown key — i.e. a YAML mapping. Callers must not call it for an element declaring
 *  `ElementDefinition.strictBody` (see `sendToSidebar`, the only caller); those blocks are
 *  found with `findFenceByBody` below instead. */
export function ensureAnchor(body: string): { body: string; id: string } {
	const existing = readAnchor(body);
	if (existing) return { body, id: existing };

	const id = generateAnchorId();
	const eol = detectEol(body);
	const trimmed = body.replace(/\s+$/, '');
	const newBody = trimmed.length > 0 ? `${trimmed}${eol}${ANCHOR_KEY}: ${id}` : `${ANCHOR_KEY}: ${id}`;
	return { body: newBody, id };
}

/**
 * SC-153 — the PROVENANCE marker: "this block was generated by the block whose
 * `_dse_anchor` is <id>". Distinct from `ANCHOR_KEY` on purpose: an anchor answers "which
 * block is this" (identity), while this answers "which block made it" (parentage), and a
 * generated block routinely carries BOTH — its own anchor once pinned, plus the id of its
 * generator. The encounter builder writes it into the `ds-initiative` block it generates so
 * that pressing "Open in sidebar" a second time refreshes that block instead of appending
 * another one.
 *
 * Same round-trip contract as ANCHOR_KEY, and it holds for the same reason: initiative's
 * `parse` mutates-and-returns the raw YAML object and `serialize` is `stringifyYaml(model)`,
 * so an unknown top-level key survives a save with no passthrough field (verified by
 * test/dom/framework/sidebarEncounterHandoff.test.ts's round-trip case). Neither the
 * encounter nor the initiative element declares a JSON schema, so — unlike ANCHOR_KEY,
 * which `pipeline.ts`'s `dataForSchemaValidation` must hide from validation — this key
 * needs no such exemption today. If either element ever gains an
 * `additionalProperties: false` schema, this key must be hidden there too.
 */
export const GENERATED_FROM_KEY = '_dse_from';
const GENERATED_FROM_LINE = new RegExp(
	`^${GENERATED_FROM_KEY}:\\s*['"]?([A-Za-z0-9_-]+)['"]?\\s*$`,
	'm',
);

/** Reads the `_dse_from:` value out of a block body, or null if absent/malformed. */
export function readGeneratedFrom(body: string): string | null {
	const match = GENERATED_FROM_LINE.exec(body);
	return match ? match[1] : null;
}

/**
 * The provenance counterpart of `findAnchoredBlock`: the first ```` ```<alias> ```` block in
 * `content` whose body carries `_dse_from: <generatorId>`. Returns null when the generator
 * has never produced one here (or the user deleted it), which the caller reads as "create
 * one", never as an error.
 */
export function findGeneratedBlock(
	content: string,
	alias: string,
	generatorId: string,
): BlockInfo | null {
	for (const block of iterateFences(content, alias)) {
		if (readGeneratedFrom(block.body) === generatorId) return block.info;
	}
	return null;
}

/** Reads the `_dse_anchor:` value out of a block body, or null if absent/malformed. */
export function readAnchor(body: string): string | null {
	const match = ANCHOR_LINE.exec(body);
	return match ? match[1] : null;
}

/**
 * Scans `content` (a whole note's text) top-down for a ```` ```<alias> ```` (or
 * `~~~`-fenced) block whose body contains `_dse_anchor: <id>`. Returns the fence's
 * position (fence lines inclusive), or null when no such block exists — the caller (the
 * sidebar host) reads that as "not addressable right now" (block deleted/renamed/note
 * edited out from under the panel), never throws.
 *
 * Fences don't nest (CommonMark): a full top-down scan threading open/close state is used
 * rather than a naive "first fence-looking line" walk, so a fence-marker-looking line
 * inside an open block's own content (wrong char, too short, or carrying an info string)
 * is correctly treated as literal content instead of a spurious close.
 */
export function findAnchoredBlock(content: string, alias: string, id: string): BlockInfo | null {
	for (const block of iterateFences(content, alias)) {
		if (readAnchor(block.body) === id) return block.info;
	}
	return null;
}

/**
 * The un-anchored counterpart: the FIRST ```` ```<alias> ```` (or `~~~`) block in `content`,
 * regardless of whether it already carries an anchor — `listFences(content, alias)[0]`.
 * `sendToSidebar` (spec §1.7) computes `listFences` itself for the ambiguity check and reuses
 * that array rather than calling this a second time, but this is the small standalone form
 * for any caller that just wants "the first one" (e.g. a future no-cursor entry point).
 */
export function findFirstFence(content: string, alias: string): BlockInfo | null {
	return listFences(content, alias)[0] ?? null;
}

/**
 * SC-158 — the CONTENT-ADDRESSED counterpart of `findAnchoredBlock`, for elements whose
 * body the framework must not write into (`ElementDefinition.strictBody`). Those blocks
 * carry no `_dse_anchor:` line, so their identity is the body text itself: the first
 * ```` ```<alias> ```` block whose body matches `body` exactly.
 *
 * This is a weaker identity than a stamped id and deliberately so — it is what buys a
 * byte-identical note. It survives arbitrary line drift elsewhere in the note (the whole
 * point of the anchor mechanism) and only loses the binding if the block's OWN body is
 * edited, at which point "this is no longer the thing you pinned" is a defensible reading.
 * `SidebarBlockHost` softens even that: in a note with a single block of the alias it
 * re-binds to it rather than degrading.
 *
 * Trailing whitespace is normalized on both sides, mirroring `ensureAnchor`'s own
 * `body.replace(/\s+$/, '')`, so a trailing blank line inside the fence can't desync a
 * binding the user never touched.
 */
export function findFenceByBody(content: string, alias: string, body: string): BlockInfo | null {
	const wanted = body.replace(/\s+$/, '');
	for (const block of iterateFences(content, alias)) {
		if (block.body.replace(/\s+$/, '') === wanted) return block.info;
	}
	return null;
}

/**
 * Every ```` ```<alias> ```` (or `~~~`) block in `content`, top-down, in encounter order.
 * `sendToSidebar` uses the length of this to decide whether picking "first" is actually
 * ambiguous (worth a `Notice`) — see registration.ts.
 */
export function listFences(content: string, alias: string): BlockInfo[] {
	return [...iterateFences(content, alias)].map((block) => block.info);
}

/**
 * The ```` ```<alias> ```` (or `~~~`) block whose fence lines (inclusive) contain `line`,
 * or null when `line` doesn't sit inside one. Used by `sendToSidebar` (spec §1.7 / review
 * finding #3) to bind the occurrence nearest the cursor rather than always the first, when
 * a note has multiple blocks sharing the same alias.
 */
export function findFenceAtLine(content: string, alias: string, line: number): BlockInfo | null {
	for (const info of listFences(content, alias)) {
		if (line >= info.lineStart && line <= info.lineEnd) return info;
	}
	return null;
}

/** Matches a fence-marker line, trimming the rest-of-line into either the info string or
 *  empty. Null when `line` isn't a fence marker at all. Exported (with `isFenceClose`
 *  below) so registration.ts's `aliasAtLine` — a live-Editor, prefix-scan variant of this
 *  same open/close matching, needed because it must recognize a fence that's open but
 *  not yet closed (the cursor sitting inside a block the user is still typing) — builds
 *  its open/close test on the exact same primitives instead of a second hand-rolled copy. */
export function matchFenceLine(line: string): { marker: string; rest: string } | null {
	const match = FENCE_LINE.exec(line);
	return match ? { marker: match[1], rest: match[2].trim() } : null;
}

/**
 * SC-184 fix round (MEDIUM-2b) — a fence's ALIAS is only the first whitespace-delimited
 * token of its info string, never the whole trimmed rest. This mirrors what Obsidian's own
 * renderer actually keys a `registerMarkdownCodeBlockProcessor` match on (the mdast-to-hast
 * code renderer computes its `language-<x>` class from `lang.match(/^[^ \t]+(?=[ \t]|$)/)` —
 * first token only, confirmed against the installed Obsidian app bundle), and what
 * `ReadingModeBlockHost`'s own `OPEN_FENCE = /^([\`~]{3,})(\S*)/` already assumed. Before
 * this helper existed, `open.alias`/`aliasAtLine`'s `alias` were the FULL trimmed rest —
 * so a fence carrying extra info-string content past the language token (e.g.
 * ```` ```ds-counter extra ````) had a "language" that agreed with nothing else in the
 * codebase: `registry.get()` (keyed by the bare language token) and the chrome pin item's
 * `getBlockInfo().language` (also first-token-only) could never match it. Exported so both
 * `iterateFences` below and registration.ts's `aliasAtLine` derive an alias the exact same
 * way — one identity, not two independently-evolving ones. */
export function fenceAlias(rest: string): string {
	return rest.split(/\s+/)[0] ?? '';
}

/** True when `line` is a valid CLOSE for a fence opened with `open` — same character,
 *  at least as long, and carrying no info string of its own (a bare close). */
export function isFenceClose(open: { fenceChar: string; fenceLen: number }, line: string): boolean {
	const match = matchFenceLine(line);
	return !!match && match.rest === '' && match.marker[0] === open.fenceChar && match.marker.length >= open.fenceLen;
}

/**
 * Shared fence scanner: yields every CLOSED fence block found in `content`, top-down, with
 * its alias/position/body text, regardless of alias — `findAnchoredBlock`/`listFences`
 * filter by alias afterward. Uniform bracket matching (review finding #4, CRITICAL): opens
 * on ANY fence-marker line, whatever its language token, and only treats the region as
 * closed when a bracket-matching close (same char, length >= open length, no info string)
 * is found — mirroring registration.ts's `aliasAtLine`. This is what makes a
 * fence-marker-looking line INSIDE an already-open region (wrong char, too short, or
 * carrying an info string — e.g. a `_dse_anchor`-lookalike nested in an unrelated
 * ` ```md ` example fence) correctly opaque body content instead of being individually
 * tested and matched: the forward search below only ever calls `isFenceClose` on body
 * lines, never `matchFenceLine`-as-an-opener, so a nested "```ds-counter" body line can
 * never re-open state mid-region.
 *
 * A fence-open that never finds a valid close before EOF is NOT treated as opaque through
 * to EOF (that would let one malformed/truncated fence anywhere earlier in the note
 * permanently hide every real block after it — the second consequence flagged by finding
 * #4). Instead that single candidate open is abandoned (treated as ordinary content) and
 * the scan resumes on the very next line, so a later well-formed block is still found.
 */
function* iterateFences(content: string, alias: string): Generator<{ info: BlockInfo; body: string }> {
	const lines = content.split('\n');
	let i = 0;
	while (i < lines.length) {
		const openMatch = matchFenceLine(lines[i]);
		if (!openMatch) {
			i++;
			continue;
		}
		const open = { fenceChar: openMatch.marker[0], fenceLen: openMatch.marker.length, alias: fenceAlias(openMatch.rest) };
		let j = i + 1;
		while (j < lines.length && !isFenceClose(open, lines[j])) j++;
		if (j >= lines.length) {
			// Unterminated — lenient recovery, see doc above: don't abandon the whole
			// scan, just this one candidate open.
			i++;
			continue;
		}

		if (open.alias === alias) {
			yield { info: { language: open.alias, lineStart: i, lineEnd: j }, body: lines.slice(i + 1, j).join('\n') };
		}
		i = j + 1;
	}
}
