export type GlyphVariant =
    | 'area'
    | 'burst'
    | 'villain action'
    | 'malice'
    | 'melee'
    | 'special'
    | 'ranged'
    | 'self'
    | 'versatile'
    | 'melee and ranged'
    | 'ranged and melee'
    | 'area of effect'
    | 'aoe'
    | 'activation'
    | 'triggered action'
    | 'trait'
    | 'target'
    | 'targets'
    | 'tier 1'
    | 'tier1'
    | 't1'
    | 'tier 2'
    | 'tier2'
    | 't2'
    | 'tier 3'
    | 'tier3'
    | 't3'
    | 'note1'
    | 'note2'
    | 'high dash'
    | 'chevron'
    | 'chevron-diamond'
    | 'diamond'
    | 'diamond-s'
    | 'diamond-m'
    | 'diamond-l'
    | 'a'
    | 'i'
    | 'm'
    | 'p'
    | 'r'
    | 'agility'
    | 'intuition'
    | 'might'
    | 'presence'
    | 'reason'
    | 'a-rounded'
    | 'i-rounded'
    | 'm-rounded'
    | 'p-rounded'
    | 'r-rounded'
    | 'agility-rounded'
    | 'intuition-rounded'
    | 'might-rounded'
    | 'presence-rounded'
    | 'reason-rounded'
    | 'a-block'
    | 'i-block'
    | 'm-block'
    | 'p-block'
    | 'r-block'
    | 'agility-block'
    | 'intuition-block'
    | 'might-block'
    | 'presence-block'
    | 'reason-block'
    | '1'
    | '2'
    | '3'
    | '4'
    | '5'
    | '6'
    | '7'
    | '8'
    | '9'
    | '0'
    | '0-block'
    | '1-block'
    | '2-block'
    | '3-block'
    | '4-block'
    | '5-block'
    | '6-block'
    | '7-block'
    | '8-block'
    | '9-block'
    | '0-block'
    | 'block-start'
    | 'block-space'
    | 'block-end'
    | '-'
    | '<'
    | '='
    | '>'
    | '*'
    | '/'
    | 'weak'
    | 'average'
    | 'strong';
