export interface SkillInfo {
	name: string;
	use: string;
}

export const SKILL_DATA: { [groupName: string]: SkillInfo[] } = {
	"crafting": [
		{ name: "alchemy", use: "Make bombs and potions" },
		{ name: "architecture", use: "Create buildings and vehicles" },
		{ name: "blacksmithing", use: "Forge metal armor and weapons" },
		{ name: "fletching", use: "Make ranged weapons and ammunition" },
		{ name: "forgery", use: "Create false badges, documents, and other items" },
		{ name: "jewelry", use: "Create bracelets, crowns, rings, and other jewelry" },
		{ name: "mechanics", use: "Build machines and clockwork items" },
		{ name: "tailoring", use: "Craft cloth and leather clothing" },
	],
	"exploration": [
		{ name: "climb", use: "Move up vertical surfaces" },
		{ name: "drive", use: "Control vehicles" },
		{ name: "endurance", use: "Remain engaged in strenuous activity over a long period" },
		{ name: "gymnastics", use: "Move across unsteady or narrow surfaces, and tumble" },
		{ name: "heal", use: "Use mundane first aid" },
		{ name: "jump", use: "Leap vertical and horizontal distances" },
		{ name: "lift", use: "Pick up, carry, and throw heavy objects" },
		{ name: "navigate", use: "Read a map and travel without becoming lost" },
		{ name: "ride", use: "Ride and control a mount who isn't sapient, such as a horse" },
		{ name: "swim", use: "Move through deep liquid" },
	],
	"interpersonal": [
		{ name: "brag", use: "Impress others with stories of your deeds" },
		{ name: "empathize", use: "Relate to someone on a personal level" },
		{ name: "flirt", use: "Attract romantic attention from someone" },
		{ name: "gamble", use: "Make bets with others" },
		{ name: "handle animals", use: "Interact with animal wildlife that isn't sapient" },
		{ name: "interrogate", use: "Obtain information from a creature withholding it" },
		{ name: "intimidate", use: "Awe or scare a creature" },
		{ name: "lead", use: "Inspire people to action" },
		{ name: "lie", use: "Convince someone that a falsehood is true" },
		{ name: "music", use: "Perform music vocally or with an instrument" },
		{ name: "perform", use: "Engage in dance, oratory, acting, or other physical performance" },
		{ name: "persuade", use: "Convince someone to agree with you through use of your charms and grace" },
		{ name: "read person", use: "Read the emotions and body language of other creatures" },
	],
	"intrigue": [
		{ name: "alertness", use: "Intuitively sense the details of your surroundings" },
		{ name: "conceal object", use: "Hide an object on your person or in your environment" },
		{ name: "disguise", use: "Change your appearance to look like a different person" },
		{ name: "eavesdrop", use: "Actively listen to something that is hard to hear" },
		{ name: "escape artist", use: "Escape from bonds such as rope or manacles" },
		{ name: "hide", use: "Conceal yourself from others' observation" },
		{ name: "pick lock", use: "Open a lock without using the key" },
		{ name: "pick pocket", use: "Steal an item that another person wears or carries without them noticing" },
		{ name: "sabotage", use: "Disable a mechanical device such as a trap" },
		{ name: "search", use: "Actively search an environment for important details and items" },
		{ name: "sneak", use: "Move silently" },
		{ name: "track", use: "Follow a trail that another creature has left behind" },
	],
	"lore": [
		{ name: "culture", use: "Knowing about a culture's customs, folktales, and taboos" },
		{ name: "criminal underworld", use: "Knowing about criminal organizations, their crimes, relationships, and leaders" },
		{ name: "history", use: "Knowing about significant past events" },
		{ name: "magic", use: "Knowing about magical places, spells, rituals, items, and phenomena" },
		{ name: "monsters", use: "Knowing monster ecology, strengths, and weaknesses" },
		{ name: "nature", use: "Knowing about natural flora, fauna, and weather" },
		{ name: "psionics", use: "Knowing about psionic places, spells, rituals, items, and phenomena" },
		{ name: "religion", use: "Knowing about religious mythology, practices, and rituals" },
		{ name: "rumors", use: "Knowing gossip, legends, and uncertain truths" },
		{ name: "society", use: "Knowing noble etiquette and the leadership and power dynamics of noble families" },
		{ name: "timescape", use: "Knowing about the various planets of the timescape" },
	],
};
